// Generated by CoffeeScript 1.10.0
(function() {
  var filesys, http, path, url, util;

  util = require("util");

  http = require("http");

  path = require("path");

  url = require("url");

  filesys = require("fs");

  http.createServer(function(request, response) {
    var full_path, my_path;
    my_path = url.parse(request.url).pathname;
    full_path = path.join(process.cwd(), my_path);
    return filesys.exists(full_path, function(exists) {
      if (!exists) {
        response.writeHeader(404, {
          "Content-Type": "text/plain"
        });
        response.write("404 Not Found\n");
        return response.end();
      } else {
        return filesys.readFile(full_path, "binary", function(err, file) {
          if (err) {
            response.writeHeader(500, {
              "Content-Type": "text/plain"
            });
            response.write(err + "\n");
            return response.end();
          } else {
            response.writeHeader(200);
            response.write(file, "binary");
            return response.end();
          }
        });
      }
    });
  }).listen(8080);

}).call(this);
