// Generated by CoffeeScript 1.10.0
(function() {
  var http, options, req;

  http = require("http");

  options = {
    protocol: "http:",
    hostname: "www.google.com",
    path: "/",
    port: 80,
    method: "GET"
  };

  req = http.request(options, function(res) {
    console.log("status: " + res.statusCode);
    console.log("headers: " + (JSON.stringify(res.headers)));
    res.setEncoding("utf8");
    return res.on('data', function(chunk) {
      return console.log("body: " + chunk);
    });
  });

  req.on("error", function(e) {
    return console.log("error: " + error);
  });

  req.end();

}).call(this);
