// Generated by CoffeeScript 1.10.0
(function() {
  var my_http, util;

  util = require("util");

  my_http = require("http");

  my_http.createServer(function(request, response) {
    console.log("I got kicked");
    response.writeHeader(200, {
      "Content-Type": "text/plain"
    });
    response.write("Hello World");
    return response.end();
  }).listen(8080);

  console.log("Server Running on 8080");

}).call(this);
