// Generated by CoffeeScript 1.10.0
(function() {
  var assert, close_database, delete_documents, documents, insert_documents, mongo, open_database, root, url;

  assert = require("assert");

  mongo = require("mongodb").MongoClient;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  url = "mongodb://localhost:27017/nodejs_server";

  root.db = null;

  open_database = function() {
    return mongo.connect(url, function(err, db) {
      assert.equal(null, err);
      root.db = db;
      return console.log("connected to server");
    });
  };

  close_database = function() {
    root.db.close();
    return root.db = null;
  };

  insert_documents = function(docs) {
    var collection;
    assert.notEqual(root.db, null);
    collection = root.db.collection("documents");
    return collection.insertMany(docs, function(err, result) {
      assert.equal(err, null);
      assert.equal(docs.length, result.result.n);
      assert.equal(docs.length, result.ops.length);
      return console.log("inserted " + docs.length + " documents into the document collection");
    });
  };

  delete_documents = function(doc) {
    var collection;
    assert.notEqual(root.db, null);
    collection = root.db.collection("documents");
    return collection.deleteMany(doc, function(err, result) {
      assert.equal(err, null);
      return console.log("deleted " + result.result.n + " documents from the document collection");
    });
  };

  documents = [
    {
      name: "Jesse Frush",
      age: 28,
      ssn: "555-55-5555"
    }, {
      name: "Apu Dutta",
      age: 22,
      ssn: "111-222-3333"
    }, {
      name: "Ash",
      age: 34,
      ssn: "555-66-7777"
    }
  ];

  open_database();

  setTimeout(delete_documents.bind(root, documents[2]), 2000);

  setTimeout(close_database, 10000);

}).call(this);
